{% set name = "cusignal" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - scipy>=1.5.0
    - numpy>=1.17.3
    - boost
    - numba>=0.49.0
    - cupy>=7.2.0,<8.0.0a0

test:
  imports:
    - cusignal

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: ../../../LICENSE
  summary: cuSignal core library
  dev_url: https://github.com/rapidsai/cusignal
